[package]
name = "kapot-wire"
version = { workspace = true }
license = "Apache-2.0"
homepage = "https://github.com/apache/arrow-kapot"
repository = "https://github.com/apache/arrow-kapot"
readme = "README.md"
authors = ["Apache DataFusion <dev@datafusion.apache.org>"]
edition = "2024"

[dependencies]
pgwire = "0.28"
tokio = { workspace = true, features = ["macros"] }
futures = { workspace = true }
log = { workspace = true }
async-trait = { workspace = true }